// Azkin — Autor: Athan Espinoza (GitHub: athomo001)
import { Injectable, signal, effect } from '@angular/core';

// AZ-020: diccionario a nivel de módulo (antes se reconstruía en cada llamada a t()).
// `TranslationKey` deriva de sus propias claves: un typo en `lang.t('clave.inexistente')`
// ahora es un error de compilación en vez de devolver silenciosamente la clave cruda en runtime.
const TRANSLATIONS = {
      'app.title': { es: 'Azkin', en: 'Azkin' },
      'nav.dashboard': { es: 'Dashboard', en: 'Dashboard' },
      'nav.settings': { es: 'Configuración', en: 'Settings' },
      'nav.logout': { es: 'Salir', en: 'Logout' },
      'sidebar.newMonitor': { es: 'Añadir Nuevo Monitor', en: 'Add New Monitor' },
      'sidebar.groups': { es: 'Grupos', en: 'Groups' },
      'sidebar.allMonitors': { es: 'Todos los Monitores', en: 'All Monitors' },
      'stats.latencyActual': { es: 'Latencia Actual', en: 'Current Latency' },
      'stats.latencyAvg': { es: 'Latencia Promedio', en: 'Average Latency' },
      'stats.uptime': { es: 'Uptime 24h', en: 'Uptime 24h' },
      'stats.lastChecked': { es: 'Último Chequeo', en: 'Last Checked' },
      'stats.never': { es: 'Nunca', en: 'Never' },
      'stats.dias': { es: 'días', en: 'days' },
      'stats.checking': { es: 'Verificando...', en: 'Checking...' },
      'stats.querying': { es: 'Consultando...', en: 'Querying...' },
      'stats.noAvailable': { es: 'No disponible', en: 'Not available' },
      'stats.history': { es: 'Historial de Disponibilidad (Últimos 30 chequeos)', en: 'Availability History (Last 30 checks)' },
      'stats.operational': { es: 'Operativo', en: 'Operational' },
      'dashboard.active': { es: 'Activos', en: 'Active' },
      'dashboard.down': { es: 'Caídos', en: 'Down' },
      'dashboard.pending': { es: 'Verificando', en: 'Checking' },
      'dashboard.paused': { es: 'Pausado', en: 'Paused' },
      'dashboard.funcional': { es: 'Funcional', en: 'Operational' },
      'dashboard.monitorsTitle': { es: 'Monitores de Red', en: 'Network Monitors' },
      // Claves de la pantalla de Configuración (Settings)
      'settings.title': { es: 'Configuración', en: 'Settings' },
      'settings.subtitle': { es: 'Administra tus canales de alerta, usuarios secundarios, seguridad y copias de seguridad.', en: 'Manage your alert channels, secondary users, security and backups.' },
      'settings.backToDashboard': { es: 'Volver al Dashboard', en: 'Back to Dashboard' },
      'settings.tabAlerts': { es: 'Canales de Alerta', en: 'Alert Channels' },
      'settings.tabViewers': { es: 'Viewers / Usuarios', en: 'Viewers / Users' },
      'settings.tabProfile': { es: 'Mi Perfil', en: 'My Profile' },
      'settings.tabBackups': { es: 'Respaldos', en: 'Backups' },
      // Formulario de Canales de Alerta
      'settings.alerts.newChannel': { es: 'Nuevo Canal de Alerta', en: 'New Alert Channel' },
      'settings.alerts.editChannel': { es: 'Editar Canal', en: 'Edit Channel' },
      'settings.alerts.channelDesc': { es: 'Define dónde enviar las notificaciones en caso de eventos.', en: 'Define where to send notifications for events.' },
      'settings.alerts.name': { es: 'Nombre Identificador', en: 'Channel Name' },
      'settings.alerts.type': { es: 'Tipo de Servicio', en: 'Service Type' },
      'settings.alerts.cancel': { es: 'Cancelar', en: 'Cancel' },
      'settings.alerts.save': { es: 'Crear Canal', en: 'Create Channel' },
      'settings.alerts.update': { es: 'Actualizar', en: 'Update' },
      'settings.alerts.activeChannels': { es: 'Canales Activos', en: 'Active Channels' },
      'settings.alerts.configured': { es: 'configurados', en: 'configured' },
      'settings.alerts.noChannels': { es: 'No hay canales de alerta configurados aún.', en: 'No alert channels configured yet.' },
      'settings.alerts.testChannel': { es: 'Probar Canal', en: 'Test Channel' },
      'settings.alerts.edit': { es: 'Editar', en: 'Edit' },
      'settings.alerts.delete': { es: 'Eliminar', en: 'Delete' },
      'settings.alerts.recipientEmail': { es: 'Dirección Destinatario', en: 'Recipient Email' },
      'settings.alerts.smtpServer': { es: 'Servidor SMTP', en: 'SMTP Server' },
      'settings.alerts.smtpHost': { es: 'Host SMTP', en: 'SMTP Host' },
      'settings.alerts.smtpPort': { es: 'Puerto', en: 'Port' },
      'settings.alerts.smtpUser': { es: 'Usuario SMTP', en: 'SMTP User' },
      'settings.alerts.smtpPass': { es: 'Contraseña SMTP', en: 'SMTP Password' },
      'settings.alerts.smtpFrom': { es: 'Remitente (From)', en: 'Sender (From)' },
      'settings.alerts.scope': { es: 'Alcance de alertas', en: 'Alert scope' },
      'settings.alerts.scopeAll': { es: 'Todas las alertas', en: 'All alerts' },
      'settings.alerts.scopeSelected': { es: 'Solo seleccionadas', en: 'Selected only' },
      'settings.alerts.scopeNone': { es: 'Ninguno', en: 'None' },
      'settings.alerts.smtpNote': { es: 'Servidor SMTP exclusivo de este canal de alerta. No afecta ni reemplaza el SMTP de recuperación de contraseña (pestaña TLS / Sistema).', en: 'SMTP server exclusive to this alert channel. Does not affect or replace the password-recovery SMTP (TLS / System tab).' },
      'settings.alerts.templateLabel': { es: 'Plantilla de mensaje', en: 'Message template' },
      'settings.alerts.preview': { es: 'Vista previa', en: 'Preview' },
      'settings.alerts.eventsLabel': { es: 'Eventos', en: 'Events' },
      'settings.alerts.channelConfigured': { es: 'Configurado', en: 'Configured' },
      // Formulario de Viewers
      'settings.viewers.createTitle': { es: 'Crear Usuario Viewer', en: 'Create Viewer User' },
      'settings.viewers.editTitle': { es: 'Editar Permisos', en: 'Edit Permissions' },
      'settings.viewers.desc': { es: 'Asigna credenciales y permisos granulares de visualización.', en: 'Assign credentials and granular view permissions.' },
      'settings.viewers.username': { es: 'Nombre de Usuario', en: 'Username' },
      'settings.viewers.email': { es: 'Correo (Opcional)', en: 'Email (Optional)' },
      'settings.viewers.password': { es: 'Contraseña', en: 'Password' },
      'settings.viewers.minChars': { es: 'Mínimo 8 caracteres', en: 'Minimum 8 characters' },
      'settings.viewers.extSession': { es: 'Extended TV Session (1 año)', en: 'Extended TV Session (1 year)' },
      'settings.viewers.granularPerms': { es: 'Permisos Granulares', en: 'Granular Permissions' },
      'settings.viewers.addPerm': { es: 'Añadir', en: 'Add' },
      'settings.viewers.createBtn': { es: 'Crear Viewer', en: 'Create Viewer' },
      'settings.viewers.updateBtn': { es: 'Actualizar Viewer', en: 'Update Viewer' },
      'settings.viewers.cancel': { es: 'Cancelar', en: 'Cancel' },
      'settings.viewers.list': { es: 'Lista de Viewers', en: 'Viewer List' },
      'settings.viewers.noViewers': { es: 'No hay Viewers creados.', en: 'No Viewers created yet.' },
      'settings.viewers.viewAll': { es: 'Ver todo (All)', en: 'View all (All)' },
      'settings.viewers.viewGroup': { es: 'Ver Grupo específico', en: 'View specific group' },
      'settings.viewers.viewMonitor': { es: 'Ver Monitor específico', en: 'View specific monitor' },
      'settings.viewers.selectGroup': { es: 'Selecciona Grupo', en: 'Select Group' },
      'settings.viewers.selectMonitor': { es: 'Selecciona Monitor', en: 'Select Monitor' },
      'settings.viewers.active': { es: 'activos', en: 'active' },
      'settings.viewers.permsLabel': { es: 'Permisos', en: 'Permissions' },
      'settings.viewers.viewAllShort': { es: 'Ver todo', en: 'View all' },
      'settings.viewers.key': { es: 'Clave', en: 'Password' },
      // Autenticación (Login y Register)
      'auth.login.title': { es: 'Ingresar', en: 'Sign In' },
      'auth.login.subtitle': { es: 'Plataforma premium de monitoreo de infraestructura', en: 'Premium infrastructure monitoring platform' },
      'auth.login.email': { es: 'Correo Electrónico', en: 'Email Address' },
      'auth.login.identifier': { es: 'Correo o Usuario', en: 'Email or Username' },
      'auth.login.password': { es: 'Contraseña', en: 'Password' },
      'auth.login.btn': { es: 'Ingresar', en: 'Sign In' },
      'auth.login.btnLoading': { es: 'Iniciando sesión...', en: 'Signing in...' },
      'auth.login.noAccount': { es: '¿No tienes una cuenta de administrador?', en: 'Don\'t have an admin account?' },
      'auth.login.registerHere': { es: 'Regístrate aquí', en: 'Register here' },
      'auth.login.error': { es: 'Credenciales incorrectas. Verifica tu usuario/correo y contraseña.', en: 'Incorrect credentials. Please verify your username/email and password.' },
      'auth.login.forgotPassword': { es: '¿Olvidaste tu contraseña?', en: 'Forgot your password?' },
      'auth.login.showPassword': { es: 'Mostrar contraseña', en: 'Show password' },
      'auth.login.hidePassword': { es: 'Ocultar contraseña', en: 'Hide password' },
      'auth.forgotPassword.subtitle': { es: 'Ingresa tu correo y te enviaremos instrucciones para recuperar tu contraseña.', en: 'Enter your email and we\'ll send you instructions to recover your password.' },
      'auth.forgotPassword.email': { es: 'Correo Electrónico', en: 'Email Address' },
      'auth.forgotPassword.btn': { es: 'Enviar instrucciones', en: 'Send instructions' },
      'auth.forgotPassword.btnLoading': { es: 'Enviando...', en: 'Sending...' },
      'auth.forgotPassword.sent': { es: 'Si el correo existe en el sistema, recibirás instrucciones para recuperar tu contraseña en breve.', en: 'If the email exists in the system, you will receive recovery instructions shortly.' },
      'auth.forgotPassword.backToLogin': { es: 'Volver al inicio de sesión', en: 'Back to login' },
      'auth.resetPassword.subtitle': { es: 'Ingresa tu nueva contraseña.', en: 'Enter your new password.' },
      'auth.resetPassword.newPassword': { es: 'Nueva Contraseña', en: 'New Password' },
      'auth.resetPassword.btn': { es: 'Restablecer contraseña', en: 'Reset password' },
      'auth.resetPassword.btnLoading': { es: 'Restableciendo...', en: 'Resetting...' },
      'auth.resetPassword.success': { es: 'Contraseña restablecida correctamente. Redirigiendo al inicio de sesión...', en: 'Password reset successfully. Redirecting to login...' },
      'auth.resetPassword.error': { es: 'El enlace de recuperación es inválido o ha expirado.', en: 'The recovery link is invalid or has expired.' },
      'auth.resetPassword.missingToken': { es: 'Falta el token de recuperación en el enlace.', en: 'The recovery token is missing from the link.' },
      'auth.register.title': { es: 'Registro de Administrador Inicial', en: 'Initial Admin Registration' },
      'auth.register.fullName': { es: 'Nombre Completo', en: 'Full Name' },
      'auth.register.btn': { es: 'Registrar Administrador', en: 'Register Administrator' },
      'auth.register.btnLoading': { es: 'Registrando...', en: 'Registering...' },
      'auth.register.hasAccount': { es: '¿Ya tienes una cuenta de administrador?', en: 'Already have an admin account?' },
      'auth.register.loginHere': { es: 'Inicia sesión aquí', en: 'Log in here' },
      'auth.register.success': { es: 'Administrador registrado correctamente. Redirigiendo...', en: 'Administrator successfully registered. Redirecting...' },
      'auth.register.error': { es: 'Error al registrar administrador. Intenta de nuevo.', en: 'Error registering administrator. Please try again.' },
      // Perfil
      'settings.profile.changeTitle': { es: 'Cambiar Contraseña Administrativa', en: 'Change Admin Password' },
      'settings.profile.changeDesc': { es: 'Establece una nueva clave para resguardar la seguridad de la consola.', en: 'Set a new key to protect console access.' },
      'settings.profile.newPass': { es: 'Nueva Contraseña', en: 'New Password' },
      'settings.profile.confirmPass': { es: 'Confirmar Nueva Contraseña', en: 'Confirm New Password' },
      'settings.profile.saveBtn': { es: 'Actualizar Contraseña', en: 'Update Password' },
      // Viewers - cambio de contraseña
      'settings.viewers.changePass': { es: 'Cambiar Contraseña', en: 'Change Password' },
      // Respaldos
      'settings.backups.sectionTitle': { es: 'Copia de Seguridad y Restauración', en: 'Backup & Restore' },
      'settings.backups.sectionDesc': { es: 'Permite portar o respaldar la configuración completa de todos tus monitores en formato JSON.', en: 'Export or restore the complete configuration of all your monitors in JSON format.' },
      'settings.backups.exportBtn': { es: 'Exportar Respaldo', en: 'Export Backup' },
      'settings.backups.exportDesc': { es: 'Descarga la lista como .json', en: 'Download configuration as .json' },
      'settings.backups.importBtn': { es: 'Importar Respaldo', en: 'Import Backup' },
      'settings.backups.importDesc': { es: 'Carga un archivo .json existente', en: 'Load an existing .json file' },
      // Comunes
      'common.cancel': { es: 'Cancelar', en: 'Cancel' },
      'common.confirm': { es: 'Confirmar', en: 'Confirm' },
      'common.save': { es: 'Guardar', en: 'Save' },
      'common.delete': { es: 'Eliminar', en: 'Delete' },
      'common.edit': { es: 'Editar', en: 'Edit' },
      // Dashboard General
      'dashboard.title': { es: 'Dashboard General', en: 'General Dashboard' },
      'dashboard.subtitle': { es: 'Monitoreo consolidado de infraestructura y agentes de red.', en: 'Consolidated infrastructure and network agent monitoring.' },
      'dashboard.statUp': { es: 'Activos (UP)', en: 'Active (UP)' },
      'dashboard.statDown': { es: 'Caídos (DOWN)', en: 'Down (DOWN)' },
      'dashboard.statPending': { es: 'Verificando (PEND.)', en: 'Checking (PEND.)' },
      'dashboard.statTotal': { es: 'Total Monitores', en: 'Total Monitors' },
      'dashboard.incidentLog': { es: 'Bitácora de Incidentes Recientes', en: 'Recent Incident Log' },
      'dashboard.refresh': { es: 'Refrescar', en: 'Refresh' },
      'dashboard.colMonitor': { es: 'Monitor', en: 'Monitor' },
      'dashboard.colStatus': { es: 'Estado', en: 'Status' },
      'dashboard.colDatetime': { es: 'Fecha/Hora', en: 'Date/Time' },
      'dashboard.colMessage': { es: 'Mensaje descriptivo', en: 'Descriptive Message' },
      'dashboard.noEvents': { es: 'Sin eventos reportados en las últimas 24 horas. Todo el sistema está operando limpiamente.', en: 'No events reported in the last 24 hours. All systems operating cleanly.' },
      // Modal de Agregar/Editar Monitor
      'monitor.modal.addTitle': { es: 'Agregar Nuevo Monitor', en: 'Add New Monitor' },
      'monitor.modal.editTitle': { es: 'Modificar Monitor', en: 'Edit Monitor' },
      'monitor.modal.subtitle': { es: 'Configura los parámetros del agente y comprobaciones.', en: 'Configure agent parameters and checks.' },
      'monitor.modal.sec1': { es: '1. Información Básica', en: '1. Basic Information' },
      'monitor.modal.name': { es: 'Nombre Descriptivo', en: 'Descriptive Name' },
      'monitor.modal.type': { es: 'Tipo de Monitor', en: 'Monitor Type' },
      'monitor.modal.target': { es: 'Target / Host / IP', en: 'Target / Host / IP' },
      'monitor.modal.sameHostLabel': { es: 'Este objetivo vive en el mismo servidor que Azkin', en: 'This target lives on the same server as Azkin' },
      'monitor.modal.sameHostHint': {
        es: 'Azkin y este objetivo corren en la misma máquina física (otro contenedor, otro Docker Compose, o un proceso nativo). Si el chequeo directo falla por red (no porque el servicio esté realmente caído), Azkin reintentará automáticamente por una ruta interna antes de marcarlo como caído.',
        en: 'Azkin and this target run on the same physical machine (another container, another Docker Compose stack, or a native process). If the direct check fails due to networking (not because the service is actually down), Azkin will automatically retry over an internal route before marking it down.',
      },
      'monitor.modal.ignoreTlsLabel': { es: 'Ignorar validación de certificado SSL/TLS', en: 'Ignore SSL/TLS certificate validation' },
      'monitor.modal.noChannelSelected': {
        es: 'Selecciona al menos un canal de notificación en "Canales de Alerta" antes de guardar — hay varios configurados y ninguno quedaría avisado si el monitor se cae.',
        en: 'Select at least one notification channel under "Alert Channels" before saving — several are configured and none would be notified if the monitor goes down.',
      },
      'monitor.modal.ignoreTlsHint': {
        es: 'Actívalo si este HTTPS usa un certificado autofirmado, vencido, o emitido por una CA interna/corporativa que tu navegador confía pero el contenedor de Azkin no (caso típico: acceder por IP en vez de dominio). Sin esto, el chequeo falla con "fetch failed" aunque el servicio esté arriba y tu navegador lo cargue sin problema.',
        en: 'Enable this if the HTTPS service uses a self-signed, expired, or internal/corporate-CA certificate that your browser trusts but the Azkin container does not (typical case: accessing by IP instead of domain). Without this, the check fails with "fetch failed" even though the service is up and loads fine in your browser.',
      },
      'monitor.modal.sec2': { es: '2. Temporizadores y Umbrales', en: '2. Timers & Thresholds' },
      'monitor.modal.interval': { es: 'Intervalo (Seg.)', en: 'Interval (Sec.)' },
      'monitor.modal.retries': { es: 'Reintentos', en: 'Retries' },
      'monitor.modal.retryInterval': { es: 'Int. Reintento (Seg.)', en: 'Retry Int. (Sec.)' },
      'monitor.modal.sec3': { es: '3. Agrupación y Clasificación', en: '3. Grouping & Classification' },
      'monitor.modal.group': { es: 'Grupo Jerárquico', en: 'Hierarchical Group' },
      'monitor.modal.tags': { es: 'Etiquetas (Separadas por Coma)', en: 'Tags (Comma Separated)' },
      'monitor.modal.sec4': { es: '4. Canales de Alerta Activos', en: '4. Active Alert Channels' },
      'monitor.modal.noChannels': { es: 'No has configurado canales de alerta todavía. Configúralos en Ajustes.', en: 'No alert channels configured yet. Set them up in Settings.' },
      'monitor.modal.sec5': { es: '5. Integridad Visual (Anti-Defacement)', en: '5. Visual Integrity (Anti-Defacement)' },
      'monitor.modal.integrityCheck': { es: 'Activar Monitoreo de Integridad Visual', en: 'Enable Visual Integrity Monitoring' },
      'monitor.modal.integrityProfile': { es: 'Perfil de Integridad', en: 'Integrity Profile' },
      'monitor.modal.integrityThreshold': { es: 'Umbral de Tolerancia', en: 'Tolerance Threshold' },
      'monitor.modal.cssSelectors': { es: 'Selectores CSS Excluidos (Comas)', en: 'Excluded CSS Selectors (Commas)' },
      'monitor.modal.snmpSec': { es: 'Campos de SNMP', en: 'SNMP Fields' },
      'monitor.modal.snmpVersion': { es: 'Versión SNMP', en: 'SNMP Version' },
      'monitor.modal.snmpPort': { es: 'Puerto SNMP', en: 'SNMP Port' },
      'monitor.modal.snmpOid': { es: 'OID a Consultar', en: 'OID to Query' },
      'monitor.modal.snmpCommunity': { es: 'Comunidad SNMP', en: 'SNMP Community' },
      'monitor.modal.snmpUser': { es: 'Usuario SNMPv3', en: 'SNMPv3 Username' },
      'monitor.modal.snmpAuthProto': { es: 'Protocolo Autenticación', en: 'Auth Protocol' },
      'monitor.modal.snmpAuthKey': { es: 'Clave Autenticación', en: 'Auth Key' },
      'monitor.modal.snmpPrivProto': { es: 'Protocolo Privacidad', en: 'Privacy Protocol' },
      'monitor.modal.snmpPrivKey': { es: 'Clave Privacidad', en: 'Privacy Key' },
      'monitor.modal.portSec': { es: 'Configuración del Puerto', en: 'Port Configuration' },
      'monitor.modal.portNum': { es: 'Número de Puerto TCP', en: 'TCP Port Number' },
      'monitor.modal.dnsSec': { es: 'Configuración del Resolutor DNS', en: 'DNS Resolver Configuration' },
      'monitor.modal.dnsResolver': { es: 'Servidor DNS Resolver', en: 'DNS Resolver Server' },
      'monitor.modal.dnsRecord': { es: 'Tipo de Registro DNS', en: 'DNS Record Type' },
      'monitor.modal.saving': { es: 'Guardando...', en: 'Saving...' },
      'monitor.modal.saveBtn': { es: 'Guardar Monitor', en: 'Save Monitor' },
      'monitor.modal.deleteTitle': { es: '¿Eliminar Monitor?', en: 'Delete Monitor?' },
      'monitor.modal.deleteMsg': { es: '¿Estás seguro de eliminar este monitor? Se borrarán permanentemente sus métricas e historial de red.', en: 'Are you sure you want to delete this monitor? Its metrics and network history will be permanently deleted.' },
      'monitor.modal.pushPassive': { es: 'Push (Pasivo)', en: 'Push (Passive)' },
      // Detalles de Monitor
      'monitor.detail.latency': { es: 'Latencia Actual', en: 'Current Latency' },
      'monitor.detail.avgLatency': { es: 'Latencia Promedio', en: 'Average Latency' },
      'monitor.detail.uptime24h': { es: 'Uptime 24h', en: 'Uptime 24h' },
      'monitor.detail.lastCheck': { es: 'Último Chequeo', en: 'Last Checked' },
      'monitor.detail.never': { es: 'Nunca', en: 'Never' },
      'monitor.detail.sslCert': { es: 'Cert. SSL', en: 'SSL Cert' },
      'monitor.detail.domainWhois': { es: 'Dominio (WHOIS)', en: 'Domain (WHOIS)' },
      'monitor.detail.days': { es: 'días', en: 'days' },
      'monitor.detail.unavailable': { es: 'No disponible', en: 'Unavailable' },
      'monitor.detail.checking': { es: 'Verificando...', en: 'Checking...' },
      'monitor.detail.querying': { es: 'Consultando...', en: 'Querying...' },
      'monitor.detail.historyTitle': { es: 'Historial de Disponibilidad (Últimos 30 chequeos)', en: 'Availability History (Last 30 checks)' },
      'monitor.detail.statusUp': { es: 'Operativo', en: 'Operational' },
      'monitor.detail.statusDown': { es: 'Caída detectada', en: 'Downtime detected' },
      'monitor.detail.statusLocalDown': { es: 'Error de red local (ISP Outage)', en: 'Local network error (ISP Outage)' },
      'monitor.detail.noData': { es: 'Sin datos', en: 'No data' },
      'monitor.detail.timeAgo30': { es: '30 chequeos atrás', en: '30 checks ago' },
      'monitor.detail.timeNow': { es: 'Ahora mismo', en: 'Just now' },
      'monitor.detail.latencyHistory': { es: 'Historial de Latencia (ms)', en: 'Latency History (ms)' },
      'dashboard.localOutageBanner': { es: '⚠️ Posible caída de conectividad local detectada (ISP Outage). Los fallos reportados durante este periodo pueden deberse a la falta de conexión del servidor de monitoreo.', en: '⚠️ Possible local network outage detected (ISP Outage). Downtimes reported during this period may be due to monitoring server disconnection.' },
      // Detalles de Grupo
      'group.detail.functional': { es: 'Funcional', en: 'Operational' },
      'group.detail.incidents': { es: 'Incidencias', en: 'Issues' },
      'group.detail.checking': { es: 'Verificando', en: 'Checking' },
      'group.detail.title': { es: 'Grupo', en: 'Group' },
      'group.detail.subtitle': { es: 'Monitoreo consolidado e historial combinado para el grupo de red.', en: 'Consolidated monitoring and combined history for the network group.' },
      'group.detail.uptime': { es: 'Uptime Consolidado', en: 'Consolidated Uptime' },
      'group.detail.latency': { es: 'Latencia Promedio', en: 'Average Latency' },
      'group.detail.agents': { es: 'Agentes Activos', en: 'Active Agents' }
} as const;

export type TranslationKey = keyof typeof TRANSLATIONS;

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  readonly currentLang = signal<'es' | 'en'>((localStorage.getItem('azkin-lang') as 'es' | 'en') || 'es');

  constructor() {
    effect(() => {
      localStorage.setItem('azkin-lang', this.currentLang());
    });
  }

  setLanguage(lang: 'es' | 'en') {
    this.currentLang.set(lang);
  }

  toggleLanguage() {
    this.currentLang.update(l => l === 'es' ? 'en' : 'es');
  }

  // Traducción basada en mapa de etiquetas básicas de la UI
  t(key: TranslationKey): string {
    return TRANSLATIONS[key][this.currentLang()];
  }
}
